constants
initialStringContent

	^ '	

## What have you done today in the image? 
...

## What have you done today with software not in the image?
...

## Changes to the Tools
...

## Changes to the Domain model
...

## Observed synergies between tools or domain models  
...
  
## Personal experience (Feelings, stories)
...

## General Observations
...

# Creativity Support Index (0: highly disaggree 10: highly aggree)

1. The system or tool allowed other people to work with me easily. 

2. It was really easy to share ideas and designs with other people inside this system or tool.

3. I would be happy to use this system or tool on a regular basis. 

4. I enjoyed using the system or tool.

5. It was easy for me to explore many different ideas, options, designs, or outcomes, using this system or tool. 

6. The system or tool was helpful in allowing me to track different ideas, outcomes, or possibilities.

7. I was able to be very creative while doing the activity inside this system or tool. 

8. The system or tool allowed me to be very expressive.

9. My attention was fully tuned to the activity, and I forgot about the system or tool that I was using. 

10. I became so absorbed in the activity that I forgot about the system or tool that I was using.

11. I was satisfied with what I got out of the system or tool. 

12. What I was able to produce was worth the effort I had to exert to produce it.

# When I am using the environment as I did today it is most important that I am able to...
'
